[workspace]
resolver = "2"
members = [
  "crates/core",
  "crates/cli",
]

[workspace.package]
version = "0.5.0"
edition = "2021"
authors = ["The Extism Authors"]
license = "BSD-Clause-3"

[workspace.dependencies]
anyhow = "1.0.68"
quickjs-wasm-rs = "^2.0.1"
