[workspace]
members = [
  "crates/core",
  "crates/cli",
]

[workspace.package]
version = "0.3.3"
edition = "2021"
authors = ["The Extism Authors"]
license = "BSD-Clause-3"

[workspace.dependencies]
anyhow = "1.0.68"

