[package]
name = "js-pdk-cli"
authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "extism-js"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
wasm-encoder = "0.20.0"
wasmparser = "0.96.0"
parity-wasm = { version = "0.45.0", features = ["bulk"] }
wizer = "1.6.0"
structopt = "0.3"
binaryen = "0.12.0"
rslint_parser = "0.3.1"