[package]
name = "js-pdk-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extism-pdk = "1.0.0-rc1"
once_cell = "1.16"
anyhow = { workspace = true }
quickjs-wasm-rs = "^2.0.1"

[lib]
crate_type = ["cdylib"]

