[package]
name = "js-pdk-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quickjs-wasm-rs = "^2.0.1"
extism-pdk = { git = "https://github.com/extism/rust-pdk"}
once_cell = "1.16"
anyhow = { workspace = true }


[lib]
crate_type = ["cdylib"]

