[package]
name = "js-pdk-core"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quickjs-wasm-rs = { git = "https://github.com/Shopify/javy" }
extism-pdk = "0.1.0"
once_cell = "1.16"
anyhow = { workspace = true }


[lib]
crate_type = ["cdylib"]
#crate_type = ["lib"]

