name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Update deps
        run: |
          ./install-wasi-sdk.sh
          go install github.com/extism/cli/extism@latest
          cd /tmp
          # get just wasm-merge and wasm-opt
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_116/binaryen-version_116-x86_64-linux.tar.gz > binaryen.tar.gz
          tar xvzf binaryen.tar.gz
          sudo cp binaryen-version_116/bin/wasm-merge /usr/local/bin
          sudo cp binaryen-version_116/bin/wasm-opt /usr/local/bin

      - name: Test
        env:
          QUICKJS_WASM_SYS_WASI_SDK_PATH: "${{ github.workspace }}/wasi-sdk"
        run: |
          make
          echo "wasm-opt: "
          echo $(which wasm-opt)
          echo "wasm-merge: "
          echo $(which wasm-merge)
          ls -lah ./target/release/
          ls -lah examples/simple_js
          ls -lah examples/
          make test
