name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-wasi

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.x'

      - name: Update deps
        run: |
          ./install-wasi-sdk.sh
          go install github.com/extism/cli/extism@latest
          sudo apt-get install binaryen

      - name: Test
        env:
          QUICKJS_WASM_SYS_WASI_SDK_PATH: "${{ github.workspace }}/wasi-sdk"
        run: |
          make
          echo "Wasm-merge: "
          echo $(which wasm-merge)
          ls -lah ./target/release/
          ls -lah examples/simple_js
          ls -lah examples/
          make test
